dataset: 'scannet'
type: "ScanNet"

preload: False
moving_distance_threshold: 1
meshing:
  resolution: 0.01 #cm # Increase this number to speed up meshing algorithm
  eval_rec: True
tracking:
  ignore_edge_W: 75
  ignore_edge_H: 75
  lr_T: 0.0005
  lr_R: 0.0025
  pixels: 2000
  iters: 10
  vis_freq: 100
  vis_inside_freq: 25
mapping:
  every_frame: 4
  keyframe_every: 1
  pixels: 2000
  edge_sample: 2000
  iters: 60
  max_drift: 3 #just for test
  vis_freq: 100
  vis_inside_freq: 60
  n_pixels: 0.05
  w_smooth: 0.001
  w_sdf_tail: 10
  w_sdf_fs: 5
  w_sdf_center: 200
  w_depth: 0.1
  w_color: 5
cam: 
  H: 480 
  W: 640
  fx: 577.590698
  fy: 578.729797
  cx: 318.905426
  cy: 242.683609
  png_depth_scale: 1000. #for depth image in png format
  crop_edge: 10
rendering:
  n_stratified: 48
  n_importance: 8
  learnable_beta: True
pos:
  enc: 'OneBlob'
  n_bins: 16
decoder:
  geo_feat_dim: 15
  hidden_dim: 32
  num_layers: 2
  num_layers_color: 2
  hidden_dim_color: 32
  tcnn_network: False
data:
  trainskip: 1
  sc_factor: 1
  downsample: 1
  translation: 0
  num_workers: 4
training: #for smoothness loss
  trunc: 0.1
  smooth_vox: 0.1
  smooth_margin: 0.05
  smooth_pts: 64
grid:
  tcnn_encoding: True

depth_scale: 1000.

frame_start: 0
frame_step: 0
frame_num: -1


orb_vocab_path: "thirdParty/ORB-SLAM2-PYBIND/Vocabulary/ORBvoc.txt"

orb_only: False
use_gt_pose: False
use_orb_backend: True
orb_useicp: True # if False, use ORB backend to track pose, otherwise use ICP to track pose
icp_use_model_depth: True
save_step: 400


uniform_sample_num: 40800

# state manage
stable_confidence_thres: 100
unstable_time_window: 120
memory_length: 5

# track params
# icp_use_model_depth: True # if False, use dataset depth frame to frame
icp_normal_threshold: 20 # degree
icp_sample_distance_threshold: 0.01 # m
icp_sample_normal_threshold: 0.01 # cos similarity

feature_lr_coef: 4.0
scaling_lr_coef: 4.0
rotation_lr_coef: 4.0