inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[0.3,9.9],[-1.0,8.0],[-1.0,3.8]]
  marching_cubes_bound: [[0.3,9.9],[-1.0,8.0],[-1.0,3.8]]
  max_drift: 3 #just for test
data:
  input_folder: /home/qm/qmslam/qmslam/data/ScanNet/scene0207
  output: output/scannet/scans/scene0207_00_max3_gloc

source_path: "data/ScanNet/scene0207"
save_path: "output/ScanNet/scene0207"

orb_settings_path: "configs/orb_config/scene0207.yaml"