dataset: 'tumrgbd'
type: "TUM"

preload: False

frame_start: 0
frame_step: 0
frame_num: -1


moving_distance_threshold: 0.5


orb_vocab_path: "thirdParty/ORB-SLAM2-PYBIND/Vocabulary/ORBvoc.txt"

orb_only: False
use_gt_pose: False
use_orb_backend: True
orb_useicp: True
icp_use_model_depth: True


meshing:
  resolution: 0.01 #cm # Increase this number to speed up meshing algorithm
  eval_rec: False
tracking:
  ignore_edge_W: 20
  ignore_edge_H: 20
  lr_T: 0.01
  lr_R: 0.002
  pixels: 5000
  iters: 200
mapping:
  mesh_freq: 5000
  max_drift: 1 # m
  every_frame: 1
  keyframe_every: 1
  pixels: 3000
  edge_sample: 2000
  iters: 60
cam:  #NOTE: intrinsic is different per scene in TUM
  H: 480
  W: 640
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  png_depth_scale: 5000.0
  crop_edge: 0
rendering:
  n_stratified: 48
  n_importance: 8
  learnable_beta: False

invalid_confidence_thresh: 0.5
# track params
# use_gt_pose: False
# icp_use_model_depth: True # if False, use dataset depth frame to frame
icp_matches_threshold: 0.2 # ratio * valie pixels
icp_normal_threshold: 20 # degree
icp_sample_distance_threshold: 0.01 # m
icp_sample_normal_threshold: 0.01 # cos similarity
tracker_max_fps: 15
icp_downscale_iters: [8, 8, 8]

# state manage
stable_confidence_thres: 200
unstable_time_window: 150
memory_length: 5