inherit_from: configs/Replica/replica.yaml

source_path: "./data/Replica/room0"
save_path: "output/Replica/room0"
data:
  input_folder: Datasets/Replica/room0
  output: output/Replica/room0
  trainskip: 1

#PLG：
mapping:
  bound: [[-1.9,7.9],[-2.2,4.5],[-2.5,2.3]]
  marching_cubes_bound: [[-1.9,7.9],[-2.2,4.5],[-2.5,2.3]]
#  bound: [[[0.0,7.9],[-2.2,4.5],[-2.5,2.3]],[[-1.9,5],[-2.2,4.5],[-2.5,2.3]]]
#  bound: [[[-1.9,3.5],[-2.2,4.5],[-2.5,2.3]],[[1.0,7.9],[-2.2,4.5],[-2.5,2.3]],[[-1.9,7.9],[-2.2,4.5],[-2.5,2.3]]]



