dataset: 'tumrgbd'
type: "TUM"

preload: False
moving_distance_threshold: 1.5
tracking:
  vis_freq: 500
  vis_inside_freq: 25
  ignore_edge_W: 25
  ignore_edge_H: 25
  const_speed_assumption: True
  gt_camera: False
  lr_T: 0.001
  lr_R: 0.001
  pixels: 2500
  iters: 50

mapping:
  #every_frame: 5
  every_frame: 2
  pixels: 3000
  edge_sample: 2000
  iters: 60
  iters_first: 1500
  lr:
    decoders_lr: 0.001
    planes_lr: 0.005
    c_planes_lr: 0.005
  ignore_edge_W: 75
  ignore_edge_H: 75
  #vis_freq: 50
  vis_freq: 1
  vis_inside_freq: 60
  ckpt_freq: 5000
  keyframe_every: 2
  w_sdf_fs: 5
  w_sdf_center: 200
  w_sdf_tail: 30
  w_depth: 0.1
  w_color: 5
  #w_smooth: 0.000001
  w_smooth: 0
  n_pixels: 0.05
  max_drift: 1.0 #just for test
  bound: [ [ -5.8,11.3 ],[ -4.0,4.5 ],[ -7.9,4.9 ] ]
  marching_cubes_bound: [ [ -5.8,11.3 ],[ -4.0,4.5 ],[ -7.9,4.9 ] ]
  mesh_freq: 15000 #
  # local_mapping_window_size: 20
  local_mapping_window_size: 15
cam:
  H: 480
  W: 640
  fx: 604.900635
  fy: 604.914063
  cx: 329.653442
  cy: 249.265564
  png_depth_scale: 1000.0 #for depth image in png format
  crop_edge: 8
data:
  input_folder: data/offfice/hall_01
  output: output/offfice/hall_01

  trainskip: 1
  sc_factor: 1
  downsample: 1
  translation: 0
  num_workers: 4

meshing:
  resolution: 0.01 #cm # Increase this number to speed up meshing algorithm
  eval_rec: True
  depth_test: True
  get_largest_components: True

pos:
  enc: 'OneBlob'
  n_bins: 16

decoder:
  geo_feat_dim: 15
  hidden_dim: 32
  num_layers: 2
  num_layers_color: 2
  hidden_dim_color: 32
  tcnn_network: False

training:
  trunc: 0.1
  smooth_vox: 0.1
  smooth_margin: 0.05
  smooth_pts: 64
grid:
  tcnn_encoding: True

model:
  c_dim: 16
  truncation: 0.1
  #input_ch: 128 #64
  input_ch: 64
  input_ch_pos: 48

#RTG：

orb_settings_path: "configs/orb_config/office.yaml"

source_path: "data/offfice/hall_01"
save_path: "output/offfice/hall_01"
depth_scale: 1000.0 #for depth image in png format
save_step: 400
frame_start: 0
frame_step: 0
frame_num: -1

uniform_sample_num: 40800

# state manage
stable_confidence_thres: 100
unstable_time_window: 120
memory_length: 5

# track params
# icp_use_model_depth: True # if False, use dataset depth frame to frame
icp_normal_threshold: 20 # degree
icp_sample_distance_threshold: 0.01 # m
icp_sample_normal_threshold: 0.01 # cos similarity

orb_only: False
use_gt_pose: False
icp_use_model_depth: True
use_orb_backend: True
orb_useicp: True

# ICP
icp_downscale_iters: [10, 10, 10]

feature_lr_coef: 4.0
scaling_lr_coef: 4.0
rotation_lr_coef: 4.0