scale: 1
verbose: False
device: "cuda:0"
keyframe_device: "cuda:0" ## Change this to "cpu" to reduce GPU memory usage
planes_res:
  coarse: 0.24
  middle: 0.15
  fine: 0.06
  ultra_fine: 0.03
  bound_dividable: 0.24
c_planes_res:
  coarse: 0.24
  middle: 0.15
  fine: 0.03
  ultra_fine: 0.015
meshing:
  level_set: 0
  resolution: 0.01 #cm # Increase this number to speed up meshing algorithm
  eval_rec: False
  mesh_bound_scale: 1.02
tracking:
  ignore_edge_W: 75
  ignore_edge_H: 75
  vis_freq: 50
  vis_inside_freq: 60
  const_speed_assumption: True
  no_vis_on_first_frame: True
  gt_camera: False
  lr_T: 0.001
  lr_R: 0.001
  pixels: 2000
  iters: 8 ###########8
  w_sdf_fs: 10
  w_sdf_center: 200
  w_sdf_tail: 50
  w_depth: 1
  w_color: 5
mapping:
  every_frame: 4
  joint_opt: False
  joint_opt_cam_lr: 0.001
  no_vis_on_first_frame: True
  no_mesh_on_first_frame: True
  no_log_on_first_frame: True
  vis_freq: 10
  vis_inside_freq: 60 #each iteration
  mesh_freq: 5000
  ckpt_freq: 2000
  keyframe_every: 1
  res_keyframe: 50 ###################################################
  gb_keyframe: 20 ############
  res_every: 10
  color_samples: 50
  depth_samples: 50  ###########################################################3
  global_mapping_window_size: 20
  local_global_mapping_window_size: 15
  local_mapping_window_size: 10
  keyframe_selection_method: 'overlap'
  lr_final_factor: 5
  lr_first_factor: 5
  lr_factor: 1
  pixels: 4000
  iters_first: 100
  iters_global: 500
  iters_final: 1000
  iters: 15 ###############15
  w_sdf_fs: 5
  w_sdf_center: 200
  w_sdf_tail: 10
  w_depth: 0.1
  w_smooth: 0
  w_color: 5
  lr:
    decoders_lr: 0.001
    planes_lr: 0.005
    c_planes_lr: 0.005
cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5 #for depth image in png format
  crop_edge: 0
rendering:
  n_stratified: 32
  n_importance: 8
  perturb: True
  learnable_beta: True
model:
  c_dim: 16
  truncation: 0.06
  #input_ch: 128 #64
  input_ch: 64
  input_ch_pos: 48

pos:
  enc: 'OneBlob'
  n_bins: 16
decoder:
  geo_feat_dim: 15
  hidden_dim: 32
  num_layers: 2
  num_layers_color: 2
  num_layers_cat: 1
  hidden_dim_color: 32
  tcnn_network: False
data:
  sc_factor: 1
  downsample: 1
  translation: 0
  num_workers: 4
training:
  trunc: 0.06
  smooth_pts: 32
  smooth_vox: 0.1
  smooth_margin: 0.05
grid:
  tcnn_encoding: True
eval_verbose: True
eval_final_verbose: False


device_list: [0]
use_tensorboard: True
record_mem: False
# verbose: False
mode: "multi process"
use_network_viewer: False
use_online_scanner: False
sync_tracker2mapper_method: "strict"
sync_tracker2mapper_frames: 5

# dataset params:
save_step: 2000
preload: False
resolution : 1
resolution_scales: [1.0]
data_device: "cuda" # only cuda work
eval: False # whether select frames for eval
eval_llff: 2 # the step for select frame tor eavl
init_mode: "depth" 

# map preprocess
min_depth: 0.3
max_depth: 5.0
depth_filter: False
invalid_confidence_thresh: 0.2
global_keyframe_num: 3

# state manage
keyframe_trans_thes: 0.3
keyframe_theta_thes: 30
stable_confidence_thres: 500
unstable_time_window: 200
KNN_num: 15
KNN_threshold: -1

# ICP
use_gt_pose: True
icp_use_model_depth: False # if False, use dataset depth frame to frame
icp_downscales: [0.25, 0.5, 1.0]
icp_damping: 0.0001
icp_downscale_iters: [5, 5, 5]
icp_distance_threshold: 0.1 # m
icp_normal_threshold: 20 # degree
icp_sample_distance_threshold: 0.01 # m
icp_sample_normal_threshold: 0.01 # cos similarity
icp_warmup_frames: 0
icp_fail_threshold: 0.02

# orb backend
use_orb_backend: False
use_orb_viewer: False
orb_vocab_path: "thirdParty/ORB-SLAM2-PYBIND/Vocabulary/ORBvoc.txt"
orb_settings_path: ""
tracker_max_fps: 15
orb_useicp: True

system_verbose: False